## Introduction to TensorFlow

## Date: 9/2/22

Properties of tensor:
- datatype 
- shape
- rank/degree of tensor
    - ex: x=3 has rank 0. 
    - Whereas, x = ['tim', 'josh', 'pim'] has rank 1, i.e., one dimensional array
    - x = [['tim', 'josh', 'pim'], ['max', 'shan', 'lex']] has rank 2, i.e., two arrays and 2 dimensions (matrix)
    

In [3]:
import tensorflow as tf

In [11]:
x = tf.Variable(['tim', 'josh', 'pim'] , tf.string)
x.shape

<tf.Variable 'Variable:0' shape=(3,) dtype=string, numpy=array([b'tim', b'josh', b'pim'], dtype=object)>

In [14]:
y = tf.Variable([['tim', 'josh', 'pim'], ['max', 'shan', 'lex']], tf.string)
y.shape

TensorShape([2, 3])

Here the shape represents the dimension, number of elements in each dimension

### Changing shape of tensors

In [15]:
x = tf.ones([1,2,3])
print(x)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)


Here, we have one list[1], withon which we have two [2] lists, where each of the two lists has 3 elements [3]. This can be reshaped in different ways as shown below. Total number of elements is $1*2*3 = 6$

In [17]:
y = tf.reshape(x, [2,3,1])
print(y)

#when you use -1 the reshape function will automatically 
#calulate how many remaining elements are there and place them
#within 2 lists
z = tf.reshape(x, [2, -1])
print(z)

tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)
